### ISSUE TITLE
Stack and variable views not populated upon pausing on breakpoint

### ISSUE THREAD

**Issue by hsivonen** [farre/midas#123]
Steps to reproduce:

1. Clone https://github.com/unicode-org/icu4x and checkout rev 681ddadc0c5e5b09997f9c011cdd9b7ce7fb0d5a
2. Create `icu4x/.vscode/launch.json` with the content:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "midas-rr",
      "request": "launch",
      "name": "Launch replay session",
      "program": "${workspaceFolder}/target/debug/icu4x-testdata-datagen",
      "trace": "Off",
      "cwd": "${workspaceFolder}",
      "rrPath": "rr",
      "gdbPath": "gdb",
      "serverAddress": "localhost:50505",
      "setupCommands": []
    }
  ]
}
```
3. Run `cargo make testdata`
4. Run the final executable in rr: `rr target/debug/icu4x-testdata-datagen`
5. Open `provider/datagen/src/source.rs` and set a breakpoint on line 49 (that reads "`uprops_root: Some(uprops_root),`") by clicking the margin.
6. Press ctrl-shift-d
7. Click the green triangle to the left of "Launch replay" near the top left of the window.
8. Choose the recording `icu4x-testdata-datagen-0` (or whatever number is the latest for you)
9. Choose the `icu4x-testdata-datagen` process.
10. Press F5 to continue from "rr trampoline code".
11. Switch to "Debug Console" and enter the command `bt` in it.

# Actual results

The "Variables" and "Call Stack" boxes in the debug sidebar are empty. The title bar of the "Call Stack" box says "Paused on breakpoint". The command `bt` in the debug console prints:
```
bt
#0  icu_datagen::source::SourceData::with_uprops (self=..., uprops_root=...) at provider/datagen/src/source.rs:49
#1  0x000055eab8010fa7 in icu4x_testdata_datagen::main () at provider/testdata/src/bin/datagen.rs:18
```

# Expected results

Expected to see the local variable `uprops_root` in the "Variables" box and expected to see the stack frames printed by `bt` in the "Call Stack" box.

**Comment by theIDinside** [comment]
Thank you for reporting this issue. Just a few quick questions, so I can eliminate some possibilities right off the bat although I have a sneaking suspicion that it might be Midas not cooperating well with the specific GDB version you have.

- What Linux distro are you using?
- What GDB version?

Seeing as how the call stack was empty (which is a pretty dead giveaway of above reason for it not displaying it properly) this is probably not what's wrong, but I figured I'd ask it anyway;
- Did you check the "Args" list? `uprops_root` is an argument to the member function/method and should be displayed there and not in the locals scope.

**Comment by hsivonen** [comment]
Confirming that this improved things: The arguments and the call stack now show up. Thanks! Nothing in local variables still. I'll see if an upgrade to Ubuntu 22.04 resolves that.
