### ISSUE TITLE
UI in VS Code is not as nice as with "rr configuration tools"

### ISSUE THREAD

**Issue by PetterS** [farre/midas#134]
With RR configuration tools I get UI like this when hitting an exception and when a watched variable changes:
![Screenshot from 2022-05-29 21-52-36](https://user-images.githubusercontent.com/772305/170889103-190d69aa-7dbb-412c-857f-177bd2e87671.png)
![Screenshot from 2022-05-29 21-52-14](https://user-images.githubusercontent.com/772305/170889100-b30e6bdd-d559-45f7-b177-5725c94a41d5.png)

With Midas the first case looks like this:
![Screenshot from 2022-05-29 21-56-35](https://user-images.githubusercontent.com/772305/170889151-5aea87ae-3b5d-4390-9b5d-9aefc2915aba.png)
and the second case I can not reproduce at all since the watched variable never triggers.

Using the same RR trace in both cases.

**Comment by theIDinside** [comment]
Thank you for leaving an issue! 

`rrcfg-tools` uses another debug adapter in the background (the `cpptools` extension). Midas is it's own "debug adapter" (both use gdb as debugger backends obviously). That being said, with the latest patch that soon will be published after some testing from my part, the features you've described above, will be a part of Midas.

Thanks yet again, I'll close this feature once I'm satisfied that I haven't introduced a ton of new bugs and when the latest commits are published to VSCode marketplace!

**Comment by PetterS** [comment]
Aha, I see. The UI I saw was the standard debugger UI.
