### ISSUE TITLE
Hang on rr replay of single-process recording

### ISSUE THREAD

**Issue by Pehrsons** [farre/midas#139]
I hit a hang replaying an rr recording of a Firefox gtest run -- which has a single process (though there is a fork that never executed).

The recording was captured like so: `./mach gtest *VideoConduit*WhileTrans* --debugger=rr`. It's a fairly standard Firefox opt, non-debug build.

Midas is of v0.5.0, with the launch config:
```
        {
            "type": "midas-rr",
            "request": "launch",
            "name": "Midas rr replay",
            "cwd": "${workspaceFolder}",
            "trace": "Off",
            "gdbPath": "gdb",
            "rrPath": "rr",
            "serverAddress": "localhost:50505",
            "setupCommands": ["set print object on", "set auto-load safe-path /"]
        },
```

The `rr terminal` shows the following and then just sits:
```
rr replay -h 127.0.0.1 -s 50505 -p 294771 -k firefox-57
pehrsons@pehrsons-X299:~/dev/m-c-3$ rr replay -h 127.0.0.1 -s 50505 -p 294771 -k firefox-57
Launch gdb with
  gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:50505' /home/pehrsons/.local/share/rr/firefox-57/mmap_hardlink_4_firefox
  ```

If I at that point run the proposed gdb command in an external terminal I can run through the recording fine from there.

**Comment by theIDinside** [comment]
Thank you for this issue! It exposed a bug in the resolving of rr replay parameters. Fix will be merged shortly.
