### ISSUE TITLE
"Step Back" should step over instead of into

### ISSUE THREAD

**Issue by sj-raima** [farre/midas#184]
The icon used for "Step Back" indicates that the intention is to "Step Back Over" similar to "Step Over" and not the current behavior which is "Step Back Into".

Stepping back over some statements are more useful and usually what we want.  However, both should be supported.

See also issue #183

**Comment by theIDinside** [comment]
Thank you for reporting this issue. I will address this immediately. Apparently, VSCode is not sending us  the "granularity" parameter as per the DAP spec, which makes `stepBack` default to "step into" (or statement; which unfortunately GDB doesn't understand and I tried getting a patch into gdb that made it understand statements, but it is unfortunately in mailing list hell, trying to explain it to them why it was useful).

But I think we want, like you say, stepBack to default to reverse-next, not reverse-step-in. But this introduces the problem of not being able to reverse-step-in, so I will add another button for this, but that will be in a future release and instead just change the default first.

**Comment by sj-raima** [comment]
Thank you for a quick fix.  I agree, `reverse-step-in` can be added trough a separate button in a later release.
