### ISSUE TITLE
[Feature Request] The launch configuration should have an element to pass options to rr

### ISSUE THREAD

**Issue by sj-raima** [farre/midas#186]
Background:  I use a wrapper script for rr to pass additional options to rr.  It would be nice if I could have those options in the launch configuration directly instead of using wrapper scripts. Useful options I use are `-e` and `-M`.

Add an element `rrOptions` that takes an array of options similar to `gdbOptions`.

**Comment by theIDinside** [comment]
Thank you for filing this issue. Great idea and well needed being a RR contributor myself this will be handy.

This feature will be prioritized
